const CONFIG = {
  whatsapp: '15555555555', // TROQUE pelo seu numero com codigo do pais
  email: 'contato@venusporthaianne.com',
  paymentLinks: { us_card: '', br_card: '', br_pix: '' },
  coupons: { VENUS10: 0.10, BEMVINDA15: 0.15 }
};

const I18N = {
  br: {
    lang:'pt-BR', locale:'pt-BR', currency:'BRL', title:'Vênus por Thaianne | Tarô, espiritualidade e autoconhecimento', description:'Vênus por Thaianne — tarô, espiritualidade e autoconhecimento com atendimentos online.',
    navAbout:'Sobre',navServices:'Consultas',navHow:'Como funciona',navFaq:'FAQ',navContact:'Contato',cart:'Carrinho',
    eyebrowHero:'TARÔ • ESPIRITUALIDADE • AUTOCONHECIMENTO',heroTitle:'Clareza para ouvir sua intuição. <em>Coragem para escolher seu caminho.</em>',heroText:'Na Vênus por Thaianne, o tarô é uma ferramenta de reflexão e leitura simbólica para iluminar possibilidades, padrões e escolhas — sem promessas absolutas e sem tirar de você o poder das próprias decisões.',seeReadings:'Ver consultas',howWorks:'Como funciona',proof1:'Atendimento individual',proof2:'100% online',proof3:'Áudios gravados',heroPill:'Tarô, presença & autoconhecimento',
    aboutEyebrow:'SOBRE A MARCA',aboutTitle:'Uma experiência íntima, elegante e sem teatro.',aboutP1:'Vênus por Thaianne nasce do encontro entre sensibilidade, simbolismo e uma leitura direta. Aqui, o tarô não é usado como sentença: ele abre espaço para perguntas melhores, percepção mais clara e decisões mais conscientes.',aboutP2:'As consultas são feitas de forma online, com cuidado, privacidade e linguagem acessível. Você recebe a leitura no seu ritmo, sem precisar marcar chamada ao vivo.',aboutLink:'Falar com Thaianne →',
    servicesEyebrow:'CONSULTAS',servicesTitle:'Escolha a leitura que combina com o seu momento.',servicesNote:'Os valores mudam automaticamente conforme o país selecionado.',
    howEyebrow:'COMO FUNCIONA',howTitle:'Simples, privado e 100% online.',step1Title:'Escolha sua consulta',step1Text:'Selecione o tipo de leitura e adicione ao carrinho.',step2Title:'Envie sua pergunta',step2Text:'Após a confirmação do pedido, você recebe as orientações para enviar sua questão.',step3Title:'Receba sua leitura',step3Text:'A interpretação é enviada online, com áudios gravados e explicação organizada.',
    quote:'“O tarô pode mostrar símbolos, padrões e possibilidades. A decisão final continua sendo sua.”',
    faqEyebrow:'PERGUNTAS FREQUENTES',faqTitle:'Antes de reservar.',faqIntro:'Tudo o que você precisa saber antes de escolher sua leitura.',q1:'A consulta é ao vivo?',a1:'Não. A proposta principal é online e assíncrona: você envia sua pergunta e recebe a leitura com áudios e interpretação.',q2:'Posso fazer perguntas sobre qualquer tema?',a2:'Sim, desde que a leitura não seja usada como substituição de atendimento médico, jurídico, psicológico ou financeiro profissional.',q3:'O tarô prevê o futuro?',a3:'A abordagem da Vênus por Thaianne é simbólica e interpretativa. A leitura trabalha tendências, contextos e possibilidades, sem prometer resultados inevitáveis.',q4:'Como recebo a leitura?',a4:'O formato inicial é por WhatsApp, com áudios gravados e, quando necessário, fotos das cartas e resumo escrito.',
    contactEyebrow:'CONTACT US',contactTitle:'Quer conversar antes de escolher sua leitura?',contactText:'Fale comigo para tirar uma dúvida sobre as consultas, entender qual leitura combina com seu momento ou receber as orientações para começar.',whatsappLabel:'WhatsApp',emailLabel:'E-mail',
    footerTagline:'Tarô • espiritualidade • autoconhecimento',privacy:'Privacidade',terms:'Termos',cartTitle:'Seu carrinho',emptyCart:'Seu carrinho está vazio.',couponPlaceholder:'Cupom de desconto',apply:'Aplicar',total:'Total',checkoutBtn:'Ir para pagamento',checkoutEyebrow:'CHECKOUT',checkoutTitle:'Finalize sua reserva',fullName:'Nome completo',email:'E-mail',phone:'WhatsApp',paymentMethod:'Forma de pagamento',card:'Cartão de crédito',pix:'Pix',consent:'Li e aceito os termos e entendo que a leitura de tarô é interpretativa e não substitui aconselhamento profissional.',continuePayment:'Continuar para pagamento',secureNote:'Nesta versão para GitHub Pages, o botão de pagamento usa links externos configuráveis. Nenhum dado de cartão é armazenado neste site.',added:'adicionada ao carrinho.',invalidCoupon:'Cupom não encontrado.',enterCoupon:'Digite um cupom.',couponApplied:'Cupom aplicado',add:'Adicionar',remove:'Remover',summary:'Resumo',cardNote:'<strong>Cartão:</strong> o pagamento será concluído em uma página segura do provedor que você configurar.',pixNote:'<strong>Pix:</strong> o pagamento será concluído no link Pix do provedor configurado.',addBefore:'Adicione uma consulta antes de continuar.'
  },
  us: {
    lang:'en-US', locale:'en-US', currency:'USD', title:'Vênus by Thaianne | Tarot, spirituality & self-knowledge', description:'Vênus by Thaianne — tarot, spirituality and self-knowledge with online readings.',
    navAbout:'About',navServices:'Readings',navHow:'How it works',navFaq:'FAQ',navContact:'Contact',cart:'Cart',
    eyebrowHero:'TAROT • SPIRITUALITY • SELF-KNOWLEDGE',heroTitle:'Clarity to hear your intuition. <em>Courage to choose your path.</em>',heroText:'At Vênus by Thaianne, tarot is a tool for reflection and symbolic interpretation, helping illuminate possibilities, patterns and choices — without absolute promises and without taking away your power to make your own decisions.',seeReadings:'View readings',howWorks:'How it works',proof1:'One-on-one reading',proof2:'100% online',proof3:'Recorded audio',heroPill:'Tarot, presence & self-knowledge',
    aboutEyebrow:'ABOUT THE BRAND',aboutTitle:'An intimate, elegant experience without the theatrics.',aboutP1:'Vênus by Thaianne was born from the meeting of sensitivity, symbolism and a direct reading style. Here, tarot is not used as a sentence: it creates room for better questions, clearer perception and more conscious decisions.',aboutP2:'Readings are provided online with care, privacy and accessible language. You receive your reading at your own pace, with no live call required.',aboutLink:'Talk to Thaianne →',
    servicesEyebrow:'READINGS',servicesTitle:'Choose the reading that fits your moment.',servicesNote:'Prices update automatically based on your selected country.',
    howEyebrow:'HOW IT WORKS',howTitle:'Simple, private and 100% online.',step1Title:'Choose your reading',step1Text:'Select the type of reading and add it to your cart.',step2Title:'Send your question',step2Text:'After your order is confirmed, you will receive instructions for sending your question.',step3Title:'Receive your reading',step3Text:'Your interpretation is delivered online through recorded audio messages and an organized explanation.',
    quote:'“Tarot can reveal symbols, patterns and possibilities. The final decision remains yours.”',
    faqEyebrow:'FREQUENTLY ASKED QUESTIONS',faqTitle:'Before you book.',faqIntro:'Everything you need to know before choosing your reading.',q1:'Is the reading live?',a1:'No. The main format is online and asynchronous: you send your question and receive the reading through audio messages and interpretation.',q2:'Can I ask about any topic?',a2:'Yes, as long as the reading is not used as a substitute for professional medical, legal, psychological or financial advice.',q3:'Does tarot predict the future?',a3:'Vênus by Thaianne uses a symbolic and interpretive approach. Readings explore trends, context and possibilities without promising inevitable outcomes.',q4:'How will I receive my reading?',a4:'The initial format is via WhatsApp, with recorded audio messages and, when helpful, photos of the cards and a written summary.',
    contactEyebrow:'CONTACT US',contactTitle:'Would you like to talk before choosing your reading?',contactText:'Reach out with questions about the readings, help choosing the right format, or guidance on how to get started.',whatsappLabel:'WhatsApp',emailLabel:'Email',
    footerTagline:'Tarot • spirituality • self-knowledge',privacy:'Privacy',terms:'Terms',cartTitle:'Your cart',emptyCart:'Your cart is empty.',couponPlaceholder:'Discount code',apply:'Apply',total:'Total',checkoutBtn:'Proceed to checkout',checkoutEyebrow:'CHECKOUT',checkoutTitle:'Complete your booking',fullName:'Full name',email:'Email',phone:'WhatsApp',paymentMethod:'Payment method',card:'Credit card',pix:'Pix',consent:'I have read and accept the terms and understand that tarot readings are interpretive and do not replace professional advice.',continuePayment:'Continue to payment',secureNote:'On this GitHub Pages version, payment buttons use configurable external links. No card information is stored on this website.',added:'added to your cart.',invalidCoupon:'Discount code not found.',enterCoupon:'Enter a discount code.',couponApplied:'Discount applied',add:'Add',remove:'Remove',summary:'Summary',cardNote:'<strong>Card:</strong> payment will be completed on the secure page of the payment provider you configure.',pixNote:'<strong>Pix:</strong> payment will be completed through the configured Pix provider link.',addBefore:'Add a reading before continuing.'
  }
};

const services=[
  {id:'essencial',icon:'✦',br:{title:'Leitura Essencial',meta:'1 pergunta • leitura objetiva',description:'Para uma questão específica que precisa de clareza, contexto e orientação simbólica.',price:135},us:{title:'Essential Reading',meta:'1 question • focused reading',description:'For one specific question that needs clarity, context and symbolic guidance.',price:25}},
  {id:'venus',icon:'♀',br:{title:'Leitura Vênus',meta:'3 perguntas • leitura aprofundada',description:'Uma leitura mais completa para observar diferentes aspectos de uma situação ou fase da vida.',price:245},us:{title:'Vênus Reading',meta:'3 questions • in-depth reading',description:'A deeper reading to explore different aspects of a situation or phase of life.',price:45}},
  {id:'caminhos',icon:'☾',br:{title:'Caminhos & Possibilidades',meta:'tiragem ampla • panorama',description:'Para explorar cenário atual, desafios, tendências, oportunidades e próximos passos possíveis.',price:350},us:{title:'Paths & Possibilities',meta:'expanded spread • overview',description:'Explore your current situation, challenges, trends, opportunities and possible next steps.',price:65}},
  {id:'amor',icon:'♡',br:{title:'Amor & Relações',meta:'tema afetivo • vínculos',description:'Leitura voltada a dinâmicas, sentimentos, limites, padrões e possibilidades no campo afetivo.',price:270},us:{title:'Love & Relationships',meta:'love • relationships',description:'A reading focused on dynamics, feelings, boundaries, patterns and possibilities in relationships.',price:50}},
  {id:'espiritual',icon:'☼',br:{title:'Direcionamento Espiritual',meta:'energia • reflexão',description:'Uma leitura focada em autoconhecimento, padrões internos, energia do momento e direcionamento pessoal.',price:270},us:{title:'Spiritual Guidance',meta:'energy • reflection',description:'A reading focused on self-knowledge, inner patterns, your current energy and personal direction.',price:50}},
  {id:'completa',icon:'✧',br:{title:'Leitura Completa',meta:'sessão premium • múltiplos temas',description:'Para quem quer uma leitura extensa, com mais espaço para perguntas e conexão entre diferentes áreas.',price:460},us:{title:'Complete Reading',meta:'premium • multiple areas',description:'An extensive reading with more space for questions and connections across different areas of life.',price:85}}
];

let country=localStorage.getItem('venusCountry')||'br';
let cart=JSON.parse(localStorage.getItem('venusCart')||'[]').map(item=>typeof item==='string'?item:item?.id).filter(Boolean);
let discount=Number(localStorage.getItem('venusDiscount')||0);
const $=s=>document.querySelector(s),t=()=>I18N[country],money=v=>new Intl.NumberFormat(t().locale,{style:'currency',currency:t().currency}).format(v),serviceData=s=>s[country];

function updateLanguage(){const tr=t();document.documentElement.lang=tr.lang;document.title=tr.title;const md=document.querySelector('meta[name="description"]');if(md)md.content=tr.description;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(tr[k]!==undefined)el.innerHTML=tr[k]});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const k=el.dataset.i18nPlaceholder;if(tr[k]!==undefined)el.placeholder=tr[k]});$('#countrySelect').value=country;updatePaymentOptions();renderServices();renderCart();}
function switchCountry(next){country=next;localStorage.setItem('venusCountry',country);updateLanguage()}
function renderServices(){$('#serviceGrid').innerHTML=services.map(s=>{const d=serviceData(s);return `<article class="service-card"><div class="service-icon">${s.icon}</div><p class="service-meta">${d.meta}</p><h3>${d.title}</h3><p>${d.description}</p><div class="service-footer"><span class="price">${money(d.price)}</span><button class="add-btn" data-id="${s.id}">${t().add}</button></div></article>`}).join('');document.querySelectorAll('.add-btn').forEach(b=>b.addEventListener('click',()=>addToCart(b.dataset.id)))}
function addToCart(id){cart.push(id);persist();renderCart();const s=services.find(x=>x.id===id);toast(`${serviceData(s).title} ${t().added}`);openCart()}
function removeFromCart(i){cart.splice(i,1);persist();renderCart()}
function persist(){localStorage.setItem('venusCart',JSON.stringify(cart));localStorage.setItem('venusDiscount',discount)}
function subtotal(){return cart.reduce((sum,id)=>{const s=services.find(x=>x.id===id);return sum+(s?serviceData(s).price:0)},0)}
function total(){return subtotal()*(1-discount)}
function renderCart(){$('#cartCount').textContent=cart.length;$('#cartItems').innerHTML=cart.length?cart.map((id,idx)=>{const s=services.find(x=>x.id===id);if(!s)return '';const d=serviceData(s);return `<div class="cart-item"><div><h4>${d.title}</h4><p>${d.meta}</p><strong>${money(d.price)}</strong></div><button class="remove" data-index="${idx}">${t().remove}</button></div>`}).join(''):`<p>${t().emptyCart}</p>`;document.querySelectorAll('.remove').forEach(b=>b.addEventListener('click',()=>removeFromCart(Number(b.dataset.index))));$('#cartTotal').textContent=money(total())}
function applyCoupon(){const code=$('#couponInput').value.trim().toUpperCase();if(CONFIG.coupons[code]){discount=CONFIG.coupons[code];$('#couponMessage').textContent=`${t().couponApplied}: ${Math.round(discount*100)}%.`}else{discount=0;$('#couponMessage').textContent=code?t().invalidCoupon:t().enterCoupon}persist();renderCart()}
function openCart(){$('#cartDrawer').classList.add('open');$('#drawerBackdrop').classList.add('show')}
function closeCart(){$('#cartDrawer').classList.remove('open');$('#drawerBackdrop').classList.remove('show')}
function openCheckout(){if(!cart.length){toast(t().addBefore);return}closeCart();$('#checkoutModal').classList.add('show');$('#checkoutModal').setAttribute('aria-hidden','false');renderCheckout()}
function closeCheckout(){$('#checkoutModal').classList.remove('show');$('#checkoutModal').setAttribute('aria-hidden','true')}
function renderCheckout(){$('#checkoutSummary').innerHTML=`<strong>${t().summary}:</strong><br>${cart.map(id=>{const s=services.find(x=>x.id===id);const d=serviceData(s);return `${d.title} — ${money(d.price)}`}).join('<br>')}<br><br><strong>${t().total}: ${money(total())}</strong>`;updatePaymentNote()}
function updatePaymentOptions(){const s=$('#paymentMethod');if(!s)return;s.innerHTML=country==='br'?`<option value="card">${t().card}</option><option value="pix">${t().pix}</option>`:`<option value="card">${t().card}</option>`;updatePaymentNote()}
function updatePaymentNote(){const s=$('#paymentMethod');if(!s)return;$('#paymentNote').innerHTML=s.value==='pix'?t().pixNote:t().cardNote}
function checkout(e){e.preventDefault();const data=new FormData(e.target),method=data.get('payment'),key=country==='br'?(method==='pix'?'br_pix':'br_card'):'us_card',link=CONFIG.paymentLinks[key];if(link){window.location.href=link;return}const order=cart.map(id=>{const s=services.find(x=>x.id===id);const d=serviceData(s);return `• ${d.title} (${money(d.price)})`}).join('\n');const payLabel=method==='pix'?'Pix':t().card;const intro=country==='br'?'Olá! Quero finalizar uma compra na Vênus por Thaianne.':'Hello! I would like to complete a purchase from Vênus by Thaianne.';const msg=encodeURIComponent(`${intro}\n\n${order}\n\n${t().total}: ${money(total())}\n${t().paymentMethod}: ${payLabel}\n${t().fullName}: ${data.get('name')}\n${t().email}: ${data.get('email')}\nWhatsApp: ${data.get('phone')}`);window.open(`https://wa.me/${CONFIG.whatsapp}?text=${msg}`,'_blank')}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}

function setupReveal(){const els=document.querySelectorAll('.reveal-on-scroll');if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('is-visible'));return}const io=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');io.unobserve(entry.target)}})},{threshold:.14});els.forEach(e=>io.observe(e))}
function setupBackToTop(){const btn=$('#backToTop');const onScroll=()=>{if(window.scrollY>420)btn.classList.add('show');else btn.classList.remove('show')};window.addEventListener('scroll',onScroll,{passive:true});btn.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));onScroll()}

$('#countrySelect').addEventListener('change',e=>switchCountry(e.target.value));$('#openCart').addEventListener('click',openCart);$('#closeCart').addEventListener('click',closeCart);$('#drawerBackdrop').addEventListener('click',closeCart);$('#applyCoupon').addEventListener('click',applyCoupon);$('#goCheckout').addEventListener('click',openCheckout);$('#closeCheckout').addEventListener('click',closeCheckout);$('#checkoutForm').addEventListener('submit',checkout);$('#paymentMethod').addEventListener('change',updatePaymentNote);$('.menu-toggle').addEventListener('click',()=>$('.nav').classList.toggle('show'));document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>$('.nav').classList.remove('show')));$('#year').textContent=new Date().getFullYear();
updateLanguage();setupReveal();setupBackToTop();
